# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - wheel_left_joint
      - wheel_right_joint
   sim_control_mode: 1 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'
  publish_rate: 50.0               # default: 50
  enable_odom_tf: False
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.35
  wheel_radius : 0.0475
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.22 # m/s
      min_velocity           : -0.22 # m/s
      has_acceleration_limits: false
      max_acceleration       : 0.05  # m/s^2
      min_acceleration       : -0.05 # m/s^2
      has_jerk_limits        : false
      max_jerk               : 0.01  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.7 # rad/s
      min_velocity           : -0.7 # rad/s
      has_acceleration_limits: false
      max_acceleration       : 0.3  # rad/s^2
      min_acceleration       : -0.3
      has_jerk_limits        : false
      max_jerk               : 0.01 # rad/s^3

medicbot_hw_main:
   my_pid1:
      p             : 120.0
      i             : 0.0
      d             : 0.0
      i_clamp_min   :  -1.0
      i_clamp_max   :  1.0
      publish_state  : true
   my_pid2:
      p             : 120.0
      i             : 0.0
      d             : 0.0
      i_clamp_min   :  -1.0
      i_clamp_max   :  1.0
      publish_state  : true
